codecov:
  require_ci_to_pass: no
  max_report_age: off

comment: false

coverage:
  precision: 2
  round: down
  status:
    project:
      default:
        target: 95
        informational: true
    patch: off
    changes: off
    
ignore:
  - "setup.py"
  - "pyproject.toml"
  - "xwavelet/test/*"
  - "xwavelet/__init__.py"
  - "xwavelet/_version.py"
