name: test_env_xwavelet
channels:
  - conda-forge
  - defaults
dependencies:
  - xarray
  - dask
  - numpy
  - numpy_groupies
  - pytest
  - pip
  - black
  - cftime
  - setuptools
  - xrft
  - xoa
  - pip:
    - codecov
    - pytest-cov
    - pytest-xdist
    - setuptools-scm
    - toml
